### ISSUE TITLE
Follow WordPress Coding Standards

### ISSUE THREAD

**Issue by Zodiac1978** [webgilde/advanced-ads-genesis#2]
As a test for our bigger plugins I would like to refactor this plugin to follow the WordPress coding standards.

See: https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/

Further links:
https://make.wordpress.org/tide/
https://github.com/wptide
https://wptide.org/

**Comment by webzunft** [comment]
@Zodiac1978 great idea. How would you proceed with this?

**Comment by Zodiac1978** [comment]
I have set up WPCS for my editor (Sublime text 3) with this tutorial yesterday:
https://gist.github.com/GaryJones/0604e6cd94eae756436740ad70f92ff8

Now I'm looking through the files manually and start to commit those changes.

There are still some warnings and errors I don't want to touch without discussion. Maybe we could talk about those things after I am finished with the first walkthrough of this plugin. After that we will see how much work needs to be done for all plugins.

**Comment by Zodiac1978** [comment]
Hey @webzunft - I finished my first review with just a quick fix of all the low hanging fruits.

These are the still open warnings/errors so far:

**genesis-ads.php:**

- Missing @package tag in file comment

**/admin/admin.php:**

- Class file names should be based on the class name with "class-" prepended. Expected class-advanced-ads-genesis-admin.php, but found admin.php.
- Missing file doc comment
- Missing class doc comment
- All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '__'.
- A gettext call containing placeholders was found, but was not accompanied by a "translators:" comment on the line above to clarify the meaning of the placeholders.
- Parameter comment must end with a full stop
- Parameter comment must end with a full stop
- Expected 4 spaces after parameter type; 1 found
- Parameter comment must end with a full stop
- All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '__'.
- All output should be run through an escaping function (like esc_html_e() or esc_attr_e()), found '_e'.
- All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$placement_slug'.
- All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$_group'.
- All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$_position'.
- All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '__'.
- A gettext call containing placeholders was found, but was not accompanied by a "translators:" comment on the line above to clarify the meaning of the placeholders.


**/classes/plugin.php:**

- Class file names should be based on the class name with "class-" prepended. Expected class-advanced-ads-genesis-plugin.php, but found plugin.php.
- Missing file doc comment
- Missing short description in doc comment
- Missing @var tag in member variable comment
- Missing function doc comment
- Missing short description in doc comment
- Parenthesis should always be used when instantiating a new object.
- Whitespace found at end of line
- Whitespace found at end of line
- This comment is 56% valid code; is this commented out code?


**/public/public.php:**

- Class file names should be based on the class name with "class-" prepended. Expected class-advanced-ads-genesis.php, but found public.php.
- Missing file doc comment
- Missing class doc comment
- Found: ==. Use strict comparisons (=== or !==).
- Found: ==. Use strict comparisons (=== or !==).
- Use Yoda Condition checks, you must.

**Comment by Zodiac1978** [comment]
@webzunft I've updated the comment with line numbers
