### ISSUE TITLE
Update placement option layout

### ISSUE THREAD

**Issue by webzunft** [webgilde/advanced-ads-genesis#6]
The "position" option in the add-on is not aligned with the Advanced Ads labels. See below how it looks in the base Advanced Ads plugin and below how it looks with Genesis.

<img width="833" alt="Bildschirmfoto 2021-07-19 um 14 59 18" src="https://user-images.githubusercontent.com/2728720/126163372-dbab1cb3-9c72-4694-8adb-e8e2a0889a53.png">

@alpipego could you update it before the 5.8 release?

**Comment by alpipego** [comment]
Can you tell me how I can reproduce this? I have never worked with this plugin before, nor any Genesis theme. What are the dependencies to running this add-on?

**Comment by webzunft** [comment]
Install

- Advanced Ads
- Genesis Framework + Sample Theme and activate it
- the Advanced Ads Genesis add-on

Go to Advanced Ads > Placements and look for the Genesis placement icon.
